ruby-on-rails/getting_started/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index' => 'welcome#index'
  
  #Generates 8 routes
  resources :articles do  
    resources :comments
  end





  root to: 'articles#index'
end

ruby-on-rails/getting_started/app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, inverse_of: :article, dependent: :destroy
    validates :title, length: { minimum: 5}    
end

ruby-on-rails/getting_started/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article, inverse_of: :comments
  validates :body, :commenter , presence: true 
end

ruby-on-rails/getting_started/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def new
  end

  def index
  end

  def show
  end
end

ruby-on-rails/getting_started/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    def new
        @article = Article.new  
    end
    
    def show
        @article = Article.find(params[:id])
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)
        #binding.pry
        if @article.save
            redirect_to article_path(@article)
        else
            render '/articles/show'
        end
    end

    def update
        #render plain: params.inspect
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    private 

    def article_params
        params.require(:article).permit(:title,:body)
    end
end

ruby-on-rails/getting_started/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comment = Comment.new(comment_params)
        @comment.article = @article
        if @comment.save
            redirect_to article_path(@comment.article)
        else
            render article_path(@comment.article)
        end

    end

    def edit
        puts params
        @comment= Comment.find(params[:id])
        @article = @comment.article
    end

    def update
        @comment = Comment.find(params[:id])
        @article = @comment.article
        if @comment.update(comment_params)
            redirect_to article_path(@article)
        else
            render 'edit'
        end

    end

    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        @article = @comment.article
        redirect_to article_path(@article)
    end


    private 
    
    def comment_params
        params.require(:comment).permit(:commenter,:body)
    end
end

ruby-on-rails/getting_started/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
        
    end
end

ruby-on-rails/getting_started/app/helpers/articles_helper.rb
module ArticlesHelper
end

ruby-on-rails/getting_started/app/helpers/comments_helper.rb
module CommentsHelper
end

ruby-on-rails/getting_started/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ruby-on-rails/getting_started/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <!-- Show error if encountered -->
   render 'shared/errors'

    <!-- Render form using helper f.form -->
    <%= f.label :title %> <br>
    <%= f.text_field :title %> <br>
    <%= f.label :body %> <br>
    <%= f.text_area :body %><br>
    <%= f.submit %>
<% end %>

ruby-on-rails/getting_started/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<!-- Return link -->
<p>
<%= link_to "Cancel", articles_path%> 
<%= link_to "Delete", article_path, method: :delete %>
</p>

ruby-on-rails/getting_started/app/views/articles/index.html.erb
<h1>Your Articles: </h1>
<%= link_to "Create", new_article_path%>
<ul>
    <% @articles.each do |a| %>
    <li> 
        <h2>
            <%= a.title.capitalize %> 
        </h2>
        <p>
            <%= a.body %>
            <%= link_to "Show", article_path(a) %>
            <%= link_to "Edit", edit_article_path(a) %>
            <%= link_to "Delete", article_path(a), method: :delete %>
        </p>
    </li>
    <% end %>
</ul>

ruby-on-rails/getting_started/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<!-- Return link -->
<p>
<%= link_to "Cancel", articles_path%>
</p>

ruby-on-rails/getting_started/app/views/articles/show.html.erb
<h1> <%= @article.title.capitalize %></h1>
<p> <%= @article.body %> </p>

<% if @article.comments.any?%>
    <h2> <%= pluralize(@article.comments.count, "Comment")%></h2>
    <ul>
        <% @article.comments.each do |comment| %>
            <li>
                <strong>
                    <%= comment.commenter.capitalize %> said: 
                </strong>
                <span> 
                    <%= comment.body%> 
                    <%= link_to "Edit",edit_article_comment_path(@article, comment) %>
                    <%= link_to "Delete", article_comment_path(@article, comment),method: :delete%>
                </span>
            </li>
        <% end %>
    </ul>
<% end %>


<h3> Add a comment</h3>
<%= form_with(model: [@article, @article.comments.build]) do |f|%>
    <%= f.label :commenter %> <br>
    <%= f.text_field :commenter %> <br>
    <%= f.label :body %> <br>
    <%= f.text_area :body %><br>
    <%= f.submit %>
<% end %>

<!-- Show errors on blank comments -->
<%= render 'shared/errors', article: @comment%>

<p>
    <%= link_to "Return back", articles_path %>
</p>

ruby-on-rails/getting_started/app/views/comments/edit.html.erb
<!-- Show article whose comment is being editted -->
<h1> <%= @article.title.capitalize %></h1>
<p> <%= @article.body %> </p>

<!-- Show error if encountered -->
<%= render 'shared/errors', object: @article%>

<!-- Show form update comment -->
<%= form_for @comment, 
    url: article_comment_path(@article, @comment), 
    method: :patch do |f| %>
        <span> <%= @comment.commenter %> </span>
        <%= f.text_area :body , :placeholder => "Body"%>
        <%= f.submit %>
<% end %>

<p><%= link_to "Cancel", article_path(@article) %></p>

ruby-on-rails/getting_started/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GettingStarted</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ruby-on-rails/getting_started/app/views/shared/_errors.html.erb
 <% if @object and @object.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@object.errors.count, "error")%> prohibited this object from being saved:
            </h2>
            <ul>
                <% @object.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

ruby-on-rails/getting_started/app/views/welcome/index.html.erb
<h1>Sup rails!</h1>