ruby-on-rails/parking/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/sessions/new' => 'sessions#new', as: :new_session
  post '/sessions' => 'sessions#create', as: :sign_in
  get '/sessions/welcome' => 'sessions#welcome', as: :welcome
  delete '/sessions' => 'sessions#destroy', as: :logout

  resources :tickets

  root to: 'sessions#welcome'
  patch '/ticket-bill/:id' => 'tickets#bill', as: :bill
end

ruby-on-rails/parking/app/models/ticket.rb
class Ticket < ApplicationRecord
    #belongs_to :vehicle_types
    validates :plate, presence: true, format: {with: /\A\w{3}[0-9]{3}\z/, message: "Format should be AAA000"}
end

ruby-on-rails/parking/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

end

ruby-on-rails/parking/app/models/vehicle_type.rb
class VehicleType < ApplicationRecord
  has_many :tickets
end

ruby-on-rails/parking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SharedHelper

end

ruby-on-rails/parking/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :authenticate_user!, except: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user and user.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in perrito !"
      @current_user = user
      redirect_to welcome_path
    else
      flash[:error] = "invalid credentials!"
      redirect_to new_session_path
    end
  end

  def destroy
    binding.pry
    session.delete(:user_id)
    flash[:success] = "Logout successfully! Vemos mi perro"
    redirect_to welcome_path
  end

  def welcome
  end

  private

  # la vuelta esa de los strongs parameters
  def session_params
    params.require(:session).permit(:email, :password)
  end

end

ruby-on-rails/parking/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    def create
        puts "This is a test #{VehicleType.find_by(name: ticketParams[:vtype])[:id]}"
        if Ticket.where(hour_out: nil).count > 9
            flash[:error] = 'No spaces available, try later'
            redirect_to root_path
            return nil
        end
        @current_car = Ticket.where("hour_out is NULL AND plate = ?", ticketParams[:plate]).first

        if @current_car
            flash[:error] = 'The vehicle has an open ticket'
            redirect_to root_path
            return nil
        end
        
        @ticket = Ticket.new(
            plate: ticketParams[:plate],
            vtype_id: VehicleType.find_by(name: ticketParams[:vtype])[:id],
            hour_in: DateTime.now,
        )
        if @ticket.save
            redirect_to ticket_path(@ticket)
        else
            flash[:error] = "Invalid content #{@ticket.errors.messages}"
            render new_ticket_path
        end
    end

    def index
    end

    def show
        @ticket = Ticket.find(params[:id])
    end

    def new
    end

    def destroy
        @ticket = Ticket.find(params[:id])
        @ticket.delete
        redirect_to root_path
    end

    def bill
        @ticket = Ticket.find(params[:id])
        @ticket.update(
            hour_out: DateTime.now,
        )
        hour_in = @ticket[:hour_in]
        hour_out = @ticket[:hour_out]
        puts "Price is #{VehicleType.find(@ticket[:vtype_id])[:price]}"
        @price = ( hour_out - hour_in)/3600 * VehicleType.find(@ticket[:vtype_id])[:price]
        @ticket.update(
            price: @price
        )
        redirect_to root_path
    end

    private

    def ticketParams
        params.require(:ticket).permit(:plate, :vtype)
    end
end

ruby-on-rails/parking/app/helpers/sessions_helper.rb
module SessionsHelper
end

ruby-on-rails/parking/app/helpers/shared_helper.rb
module SharedHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end

  def authenticate_user!
    if !user_signed_in?
      flash[:error] = "Unauthorized. Login first carechimba."
      redirect_to new_session_path
    end
  end


end

ruby-on-rails/parking/app/helpers/tickets_helper.rb
module TicketsHelper
end

ruby-on-rails/parking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parking</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:success] %>
    <span data-flash class="success"> <%= flash[:success]%> </span>
    <% elsif flash[:error]%>
    <span data-flash class="error"> <%= flash[:error]%> </span>
    <% end %>
    <%= yield %>
  </body>
</html>

ruby-on-rails/parking/app/views/tickets/new.html.erb
<h1> Create your ticket </h1>
<% @available_vehicles = []%>
<% VehicleType.all.each do |x| %>
    <%@available_vehicles << x.name  %>
<% end %>
<%= form_for :ticket, url: tickets_path, method: :post do |f|%>
    <%= f.label :plate %><br>
    <%= f.text_field :plate %><br>
    <%= f.label :vtype %><br>
    <%= f.select :vtype, @available_vehicles%><br>
    <%= f.submit %>
<% end %>
<%= link_to "Return", root_path%>

ruby-on-rails/parking/app/views/tickets/show.html.erb
<h1>Ticket <%= @ticket[:plate].upcase %> </h1>

<ul>
    <li>Type of car: <%= VehicleType.find(@ticket[:vtype_id])[:name].capitalize %></li>
    <li>Hour in: <%= @ticket[:hour_in].to_formatted_s(:short)   %></li>
    <%if @ticket[:hour_out] %>
        <li>Hour out: <%= @ticket[:hour_out].to_formatted_s(:short)   %></li>    
        <li>Cost: $<%= @ticket[:price]%></li>
    <%end%>
</ul>

<%unless @ticket[:hour_out] %>
    <%= link_to "Checkout", bill_path(@ticket), method: :patch%>
<%end%>
<%= link_to "Delete", ticket_path(@ticket), method: :delete%>
<%= link_to "Return", root_path%> 